version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: stockplay
      POSTGRES_PASSWORD: stockplay
      POSTGRES_DB: stockplay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
  api:
    build:
      context: ./api
    env_file: ./api/.env.development
    environment:
      DATABASE_URL: postgres://stockplay:stockplay@postgres:5432/stockplay
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    command: ["npm", "run", "start:dev"]
volumes:
  pgdata:
